# Generated by Django 3.0.8 on 2020-08-04 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HackuizCTF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackuiz_Taker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crct_sol', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('challenge_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HackuizCTF.Challenges')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
