# Generated by Django 3.0.8 on 2020-08-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackuizCTF', '0002_hackuiz_taker'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackuiz_taker',
            name='taker_score',
            field=models.IntegerField(default=0),
        ),
    ]
