# Generated by Django 3.0.8 on 2020-08-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackuizCTF', '0007_auto_20200805_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge_Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chlg_ans', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
