# Generated by Django 3.0.8 on 2020-08-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HackuizCTF', '0008_auto_20200805_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackuiz_taker',
            old_name='crct_sol',
            new_name='attempts',
        ),
    ]
