# Generated by Django 3.0.8 on 2020-08-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackuizCTF', '0009_auto_20200805_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chlng_taker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_flag', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
