# Generated by Django 3.0.8 on 2020-08-06 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HackuizCTF', '0010_chlng_taker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chlng_taker',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='chlng_taker',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='chlng_taker',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
